### ISSUE TITLE
load 3D Object

### ISSUE THREAD

**Issue by sobhan-zp** [ThorstenBux/artoolkit6AndroidTest#1]
hi
Thank you for this project
We run this project very easily
but
we couldn't replace any 3D object  whit default 3D Cube
can you help me?

**Comment by ThorstenBux** [comment]
Hi,

the thing with this project is that it just uses the default OpenGL shader that ARToolKit6 offers: https://github.com/ThorstenBux/artoolkit6AndroidTest/blob/master/app/src/main/java/world/augmentmy/artk6_test/ARTrackingRenderer.java#L57

To be able to render something else one would need to write his own shaders (potentially extending the Simple-Shaders).

Having said that, it seems like ARToolKit6 is no longer continued by DAQRI. For now the artoolkitX project https://github.com/artoolkitx/artoolkitx is very similar to artoolkitX so I personally would recommend to continue with this. The API is very similar and you shouldn't have much trouble migrating this project to ARToolKit6.
